# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session-ID-MD5_Base32
version:      1.01
version_from: MD5_Base32.pm
installdirs:  site
requires:
    CGI::Session:                  0
    Digest::MD5:                   0
    MIME::Base32:                  1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
